spring:

  datasource:
    url: jdbc:postgresql://localhost:5499/dma_db
    username: dma_user
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    lettuce:
      pool:
        max-connections: 10
        min-connections: 2
      # max-idle ve min-idle yerine, max-wait yerine wait-timeout kullanıyoruz
      wait-timeout: 2000  # Maksimum bekleme süresi (ms)

    # Redis bağlantı ayarları

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 60000

server:
  port: 8085
